let suga = [
    "Bột giặt",
    "Ba gọi bò",
    "Bàn chảy",
    "Bắp cải tím",
    "Bàn là",
    "Chuối",
    "Cá hồi đông lạnh",
    "Các loại hạt",
    "Cà rốt",
    "Củ cải",
    "Củ sắn",
    "Dụng cụ y tế",
    "Dụng cụ vệ sinh",
    "Đồ đóng hộp",
    "Đường cát",
    "Đường mía",
    "Gia vị muối kimchi",
    "Gia vị ướp xá xíu",
    "Khắn ướt PURI",
    "Khắn ướt UNIKU",
    "Kem đánh răng",
    "Mì hảo hảo",
    "Mì gấu đỏ",
    "Mì tương đen",
    "Nước xà phòng",
    "Nước súc miệng Listerine",
    "Nước tẩy rửa",
    "Sữa chua",
    "Sữa bắp",
    "Sữa chuối",
    "Sữa cô gái hà lan",
    "Phở bò",
    "Phở gà",
    "Phi lê cá hồi",
    "Trứng gà",
    "Trứng vịt",
    "Thịt heo",
    "Thịt bò",
    "Táo",
];

